GET {{url}}/expenses?_id=5da982bba1ae7355a4c1a0de
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVkYTk4MTVlNTg0MmUwNTUwODkzZjQ3NiIsImlhdCI6MTU3MTM5NDI2MX0.zHStF6r3XJRFee3G3dVR8kBVuFg5coQnBRJeO-aYMnU