GET {{url}}/expenses
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVkYTU2ZTQ2NzU4OTc1ODdmNTk5NjdhYSIsImlhdCI6MTU3MTM4MjE0NiwiZXhwIjoxNTcxMzgzMDQ2fQ.dRX1qVARsjWgcT1zeiNjhdNMCUQSgvuvLRRaIRgO994