GET {{url}}/expenses
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVkYTU2ZTQ2NzU4OTc1ODdmNTk5NjdhYSIsImlhdCI6MTU3MTIzNjYyMX0.FXJA4ycuB3Fsn2QWeuAG0HMdiX_5HmUzu4i0F0LVzNs
